### ISSUE TITLE
请问，当我使用了可视化docker管理面板（如堡塔）该如何在镜像启动时读入conf文件的变量？

### ISSUE THREAD

**Issue by TaoRone** [tech-fever/nezha_telegram_bot#1]
我是个docker小白……在构建的时候遇到了这么一个问题
在可视化面板中，如何写这个启动命令来实现读入conf.ini的效果？
如图：
![问题](https://user-images.githubusercontent.com/22138142/189477615-d5ee4878-8274-45bb-b425-cb1ea36b26c9.png)

**Comment by TaoRone** [comment]
从终端其实按教程操作，运行的镜像面板也会统计进去……

不过还是有点好奇……面板该如何操作……

**Comment by tech-fever** [comment]
我没用过宝塔来管理docker容器。读入配置文件和数据应该是在挂载卷那里设置。
冒号后面是容器目录，前面是服务器目录：
- ./conf.ini:/opt/nezha_telegram_bot/conf.ini
- ./data/:/opt/nezha_telegram_bot/data/

**Comment by TaoRone** [comment]
> 我没用过宝塔来管理docker容器。读入配置文件和数据应该是在挂载卷那里设置。 冒号前面是容器目录，后面是服务器目录：
> 
> * ./conf.ini:/opt/nezha_telegram_bot/conf.ini
> * ./data/:/opt/nezha_telegram_bot/data/

谢谢大佬！我试一试！

**Comment by tech-fever** [comment]
不客气！希望有帮助哦
